import Head from 'next/head';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import { GetServerSidePropsContext } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useState } from 'react';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { getMe } from '@/api/auth/get-me';
import ProfileLeftBlock from '@/components/Profile/ProfileLeftBlock';
import ProfileRightBlock from '@/components/Profile/ProfileRightBlock';
import ProfilePageLayout from '@/containers/pages/ProfilePageLayout';
import { PageWrapper } from '@/layout/PageWrapper';

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(['posts'], () =>
    getMe(context.req.cookies.unlim_accessToken ?? ''),
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      ...(await serverSideTranslations(context.locale ?? context.defaultLocale ?? '', ['common'])),
    },
  };
};

export default function Home() {
  const [isLeftBlockMobileHidden, setLeftBlockMobileHidden] = useState(true);

  return (
    <>
      <Head>
        <title>Handmade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Header />
        {isLeftBlockMobileHidden && (
          <div className="hidden 2xl:block relative">
            <ProfileLeftBlock setMobileHidden={() => setLeftBlockMobileHidden(false)} />
          </div>
        )}
        <ProfilePageLayout left={<ProfileLeftBlock />} right={<ProfileRightBlock />} />
        <Footer withMenu />
      </PageWrapper>
    </>
  );
}
