import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetServerSideProps } from 'next';

import Loading from '@/ui/Loading';

export const getServerSideProps: GetServerSideProps = async ({ locale, defaultLocale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? defaultLocale ?? '', ['common'])),
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Unlim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex items-center justify-center">
        <Loading />
      </main>
    </>
  );
}
