import Head from 'next/head';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetServerSideProps } from 'next';

import Header from '@/components/Header';
import { getPosts } from '@/api/posts/get-posts';
import MainPage from '@/containers/pages/MainPage';
import Footer from '@/components/Footer';

export const getServerSideProps: GetServerSideProps = async ({ locale, defaultLocale }) => {
  const queryClient = new QueryClient();

  await queryClient.prefetchInfiniteQuery(
    ['posts'],
    () => getPosts({ filter: { category: 'all' }, page: { page: 1 } }),
    {
      structuralSharing: (oldData, newData) => {
        return {
          pageParams: [1],
          pages: newData.pages,
        };
      },
    },
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      ...(await serverSideTranslations(locale ?? defaultLocale ?? '', ['common'])),
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Unlim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainPage />
      <Footer withMenu />
    </>
  );
}
