import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Header from '@/components/Header';
import Container from '@/layout/Container';
import MainWrapper from '@/layout/MainWrapper';
import Main from '@/layout/Main';
import Footer from '@/components/Footer';
import { getUserPosts } from '@/api/posts/get-user-posts';
import LeftBlock from '@/layout/LeftBlock';
import RightBlock from '@/layout/RightBlock';
import CategoryContainer from '@/components/CategoryContainer';
import ContactsBlock from '@/components/UserPosts/ContactsBlock';
import PostsBlock from '@/components/UserPosts/PostsBlock';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import Breadcrumbs from '@/components/Breadcrumbs';

export const getServerSideProps = async (ctx: GetServerSidePropsContext<{ id: string }>) => {
  const params = ctx.params;
  const data = await getUserPosts(params?.id ?? '');

  return {
    props: {
      posts: data.posts,
      user: data.user,
      ...(await serverSideTranslations(ctx.locale ?? ctx.defaultLocale ?? '', ['common'])),
    },
  };
};

const PostPage = ({ posts, user }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const isLaptop = useMediaQuery('(max-width: 1200px)');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isHideSearch={true} />
      <Container>
        <Main>
          {isLaptop && <Breadcrumbs className="xs:py-0" />}
          <MainWrapper className="2xl:!mt-0">
            <LeftBlock className="2xl:hidden">
              <CategoryContainer />
            </LeftBlock>
            <RightBlock
              style={{ overflow: 'unset' }}
              className="flex justify-between gap-[30px] 2xl:flex-col xs:!px-[20px] xs:!pt-[14px]"
            >
              <ContactsBlock user={user} />
              <PostsBlock posts={posts} />
            </RightBlock>
          </MainWrapper>
        </Main>
      </Container>
      <Footer />
    </>
  );
};

export default PostPage;
